using System.Collections;
using System.Collections.Generic;
//using UnityEditor.PackageManager;
using UnityEngine;
using UnityEngine.UI;

public class CustomerController : MonoBehaviour
{
    public GameObject cam; // 玩家物件
    //public GameObject camb; // 玩家物件

    public GameObject customerPrefab; // 客物件Prefab
    public GameObject cameraPrefab; // 用砀S客的z影CPrefab
    public Transform pointA; // 客起始cA
    public Transform pointB; // 客目它cB
    public float speed = 3f; // 客移拥乃俣
    public float moveDuration = 2f; // 客移拥rg（赢rg）

    public LevelManager levelManager;


    private List<GameObject> activeUIs = new List<GameObject>(); // ⒂弥械 UI 元素
    private bool isUIDisabled = false; // 追 UI 是否已被P]
    private void Start()
    {
        levelManager = FindObjectOfType<LevelManager>();

    }
    // @是公_的函担其他_本可以{用
    public void SpawnCustomerAndMove()
    {
        StartCoroutine(HandleCustomerSequence());
    }
    public void Update()
    {
        if(Input.GetKey(KeyCode.G))
        FindObjectOfType<NPCResponseManager>().ShowNPCResponse(0, 50, 100, 0);
    }

    private IEnumerator HandleCustomerSequence()
    {
        // 1. P]所有 UI K切Q到引z影C
        DisableAllUI();
        cam.gameObject.SetActive(false);
        cameraPrefab.gameObject.SetActive(true);

        // 2. 生成客K右赢
        //customerPrefab = Instantiate(customerPrefab, pointA.position, Quaternion.identity);


        float elapsed = 0f;
        while (elapsed < moveDuration)
        {
            customerPrefab.transform.position = Vector3.Lerp(pointA.position, pointB.position, elapsed / moveDuration);
            elapsed += Time.deltaTime;
            yield return null;
        }
        FindObjectOfType<NPCResponseManager>().ShowNPCResponse(0, 50, 100, 0);


        // 3. _保客最K到_目宋恢Kh除客cz影C
        //customerPrefab.transform.position = pointB.position;
       // Destroy(customerPrefab);

        // 4. 切回主z影CK原所有 UI
        cameraPrefab.gameObject.SetActive(false);

        cam.gameObject.SetActive(true);
        RestoreUI();
        

    }
    private void DisableAllUI()
    {
        if (isUIDisabled) return;

        activeUIs.Clear();
        Graphic[] graphics = FindObjectsOfType<Graphic>();
        foreach (Graphic graphic in graphics)
        {
            if (graphic.gameObject.activeSelf)
            {
                activeUIs.Add(graphic.gameObject);
                graphic.gameObject.SetActive(false);
            }
        }
        isUIDisabled = true;
    }

    private void RestoreUI()
    {
        foreach (GameObject ui in activeUIs)
        {
            if (ui != null)
            {
                ui.SetActive(true);
            }
        }
        activeUIs.Clear();
        isUIDisabled = false;
    }

}
