using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class LV1_tip_manager : MonoBehaviour
{
    public logueManager logueManager;
    public GameObject imageObject;

    // Start is called before the first frame update
    void Start()
    {
        // z查 logueManager 是否 null
        if (logueManager == null)
        {
            // 如果 null，@示e`息，K停止^m绦
            Debug.LogError("logueManager 尚未O置！ logueManager 拖到 Inspector 中的谖唬");
            return; // @K止 Start 方法的绦
        }

        // [藏D片
        imageObject.SetActive(false);
        Debug.Log("logueManagerO置！！");

        

    }

    // Update is called once per frame
    void Update()
    {
        
    }
    IEnumerator DisplayImageAndWait()
    {
        // @示D片
        imageObject.gameObject.SetActive(true);

        // 等待玩家按下任意I
        yield return new WaitUntil(() => Input.anyKeyDown);

        // 玩家按下任意I後，P]D片物件
        imageObject.gameObject.SetActive(false);
    }
    IEnumerator WaitAndDoSomething()
    {
        // 等待三秒
        yield return new WaitForSeconds(3f);

        // 等待Y束後绦械牟僮
        Debug.Log("三秒已^去了！");
        // 您可以在@e加入後m的操作，例如@示D片或悠渌功能
    }
}
