using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TransitionController : MonoBehaviour
{
    public Material skyboxMaterial;  // 用⒖寄的天空盒材|
    public float transitionSpeed = 2f; // 化速度 (每分化的次)

    private float transitionValue = 0f; // 前的^渡值
    private bool isIncreasing = true; // 用砜刂剖窃黾舆是p少

    void Update()
    {
        // 每算^渡值
        if (isIncreasing)
        {
            transitionValue += Time.deltaTime * transitionSpeed / 60f; // rgDQ榉昼
            if (transitionValue >= 0.8f)
            {
                transitionValue = 0.8f; // _保不超^0.6
                isIncreasing = false; // 改Bp少
            }
        }
        else
        {
            transitionValue -= Time.deltaTime * transitionSpeed / 60f; // rgDQ榉昼
            if (transitionValue <= 0.4f)
            {
                transitionValue = 0.4f; // _保不低於0
                isIncreasing = true; // 改B樵黾
            }
        }

        // 更新天空盒的 CubemapTransition 值
        if (skyboxMaterial != null)
        {
            skyboxMaterial.SetFloat("_CubemapTransition", transitionValue);
        }
    }
}
